sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
#    recipients:
#      - jane@doe
env:
  global:
    - VERBOSE_OUTPUT='true'
    - BEFORE_SCRIPT='echo before script, dir:$(pwd)'
    - AFTER_SCRIPT='echo after script, dir:$(pwd) && make coveralls'
  matrix:
    - COVERAGE=true USE_DEB=true ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    #- USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    #- env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
